# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0156f8f1e4c798b170c54f394af7c97520a14c77fc8db909aae5d34f1b89ff90e203e466598032ff59a84891dbe1f3feedadae154a2ae8c18416690cd8033e8

test:
  secret_key_base: 071a4fca85df797481d3d1928d2f5d04bbe8ccbc20a69e5919c7764ab06c4e1b42662c6147cf8da3924a2d4bfa3b7972c9e0237ecf5ea69d2c47d1849ce104bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
